spring.application.name=Ecom-project

#connecting database
spring.datasource.url=jdbc:h2:mem:companydata
spring.datasource.driver-class-name=org.h2.Driver
#printing query in the console
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update


